# Generated by Django 5.0.7 on 2024-07-17 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forecast', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='frequentrequest',
            options={'ordering': ['count']},
        ),
    ]
